<!DOCTYPE html>
<html lang="en-US">
<head>
    <?php if(module_exists('site-meta')): ?>
    <?= $this->meta->head($user); ?>
    <?php endif; ?>
</head>
<body>
    
    <h1><?= $user->fullname ?></h1>
    <time><?= $user->created->format('M d, Y') ?></time>
    
    <?php if($posts): ?>
        <ol>
            <?php foreach($posts as $post): ?>
            <li><a href="<?= $post->page ?>"><?= $post->title ?></a></li>
            <?php endforeach; ?>
        </ol>
    <?php endif; ?>
    
    <?php if($pagination): ?>
        <ul>
            <?php foreach($pagination as $label => $link): ?>
            <li><a href="<?= $link ?>"><?= $label ?></a></li>
            <?php endforeach; ?>
        </ul>
    <?php endif; ?>
    
    <?php if(module_exists('site-meta')): ?>
    <?= $this->meta->foot($user); ?>
    <?php endif; ?>
</body>
</html>